### ISSUE TITLE
Add install target instead of post build command

### ISSUE THREAD

**Issue by manhnt9** [zuratama/LearningOpenGLProject#1]
https://github.com/zuratama/LearningOpenGLProject/blob/a1b9d1d3eb526a24119328df029d2a8f962d5509/CMakeLists.txt#L29

Install target is more convenient and intuitive.
Project will install all exe, libs, data to a specific folder.
Reference: [Saga3D project](https://gitlab.com/InnerPieceOSS/Saga3D/)

**Comment by pepperwood998** [comment]
Enhancement added in https://github.com/zuratama/LearningOpenGLProject/commit/fb77cd04d9c8b77417cd04b8b34e6b5f7cfea4d6
